#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
    l=list()
    ones=0
    m=0
    while n!=0:
        if(n%2==0):
            l.insert(0,0)
        else:
            l.insert(0,1)
        n=n//2
    for i in range(len(l)):
        if(l[i]==1):
            ones=ones+1
            if(ones>=m):
                m=ones
        else:
            ones=0
    print(m)
